### ISSUE TITLE
Can you make an updated version for Swift 4

### ISSUE THREAD

**Issue by grahamcracker1234** [FlexMonkey/SpriteKitMotionBlur#2]
I tried doing this myself, but have been unsuccessful in doing so, do you think you could try as this I feel this would be very beneficial to me and many others.

**Comment by FlexMonkey** [comment]
Hi, unfortunately, my terms of employment with my new employer prohibit me from doing this :(

Apologies, Simon

**Comment by animaonline** [comment]
Must be a nazi-employer ;)
